version: '3.9'
services:
  frontend:
    build: frontend
    image: $COMPOSE_PROJECT_NAME-frontend:$FRONTEND_VERSION
    container_name: $COMPOSE_PROJECT_NAME-frontend
    restart: always
    environment:
      PORT: 3000
      TZ: Asia/Seoul
    networks:
      custom:
        ipv4_address: 172.10.1.10
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  nginx:
    build: nginx
    image: $COMPOSE_PROJECT_NAME-nginx:$FRONTEND_VERSION
    container_name: $COMPOSE_PROJECT_NAME-nginx
    restart: always
    environment:
      TZ: Asia/Seoul
    ports:
    - 80:80
    - 443:443
    networks:
      custom:
        ipv4_address: 172.10.1.5
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - /etc/letsencrypt/archive/stockbox.kro.kr:/etc/letsencrypt/archive/stockbox.kro.kr:ro
networks:
  custom:
    ipam:
      driver: default
      config:
      - subnet: 172.10.1.0/24
        gateway: 172.10.1.1